name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: daschewie/fuzix_gcc:latest

    steps:
    - uses: actions/checkout@v4

    - name: Make a2560k
      run: make TARGET=a2560k diskimage

    - name: Archiving to fuzix_a2560k.zip
      run: zip -r fuzix_a2560k.zip Images/a2560k

    - uses: TheDoctor0/zip-release@0.7.6
      with:
        filename: fuzix_a2560k.zip
        directory: Images/a2560k
        exclusions: filesys*
    

