name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: daschewie/fuzix_gcc:latest
    strategy:
      fail-fast: false # keep on building even if one target fails
      matrix:
        target: [a2560k,a2560x]

    steps:
    - uses: actions/checkout@v4

    - name: Make ${{ matrix.target }}
      run: make TARGET=${{ matrix.target }} diskimage
    
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: Images/${{ matrix.target }}
