name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: daschewie/fuzix_gcc:latest

    steps:
    - uses: actions/checkout@v4

    - name: Make a2560k
      run: make TARGET=a2560k diskimage
    
    - uses: actions/upload-artifact@v4
      with:
        name: a2560k
        path: Images/a2560k
