name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: daschewie/fuzix_gcc:latest

    steps:
    - uses: actions/checkout@v4

    - name: Make a2560k
      run: make TARGET=a2560k diskimage

    - name: Archive a2560k.tar.gz
      run: tar -czvf a2560k.tar.gz Images/a2560k
    
    - uses: actions/upload-artifact@v4
      with:
        path: a2560k.tar.gz
